// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit;

/// <summary>Classifies the provenance trust retained with one context contribution.</summary>
/// <remarks>
/// Values describe provenance and instruction precedence evidence; they neither grant authority nor imply
/// that content is eligible to act as an instruction. Consumers must not infer ordering from numeric values.
/// </remarks>
public enum ContextTrust
{
    /// <summary>Content authored and controlled by the AgentKit framework.</summary>
    Framework,

    /// <summary>Content supplied by an application host's policy boundary.</summary>
    HostPolicy,

    /// <summary>Content captured from the immutable agent definition.</summary>
    AgentDefinition,

    /// <summary>Content obtained from the selected workspace or project.</summary>
    Workspace,

    /// <summary>Content supplied by the authenticated user.</summary>
    User,

    /// <summary>Data returned by an authorized retrieval operation.</summary>
    RetrievedData,

    /// <summary>Data returned by a tool operation.</summary>
    ToolData,

    /// <summary>Data generated by a model.</summary>
    ModelGenerated,
}
