// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit;

/// <summary>
/// A caller-supplied key used to make one request, such as session
/// creation, safely repeatable without duplicating its effect. Submitting
/// the same operation with the same <see cref="IdempotencyKey"/> more than
/// once is expected to observe the original outcome rather than perform the
/// operation again.
/// </summary>
/// <remarks>
/// <para>
/// This type is an immutable value object with structural (ordinal,
/// textual) equality over <see cref="Value"/>. It carries no mutable state
/// itself and is safe to share and compare across threads without
/// synchronization.
/// </para>
/// <para>
/// Idempotency keys are supplied by the caller — typically a client
/// retrying a network call after an ambiguous failure — rather than
/// generated by AgentKit, because only the caller knows whether two
/// requests represent "the same attempt" or two genuinely separate
/// operations. The owning component (for example, session creation) is
/// responsible for persisting the key alongside its result long enough to
/// answer a later repeat with the same key, and for treating a reused key
/// with materially different request content as a conflict rather than a
/// silent replay.
/// </para>
/// <para>
/// This constructor only rejects null, empty, and whitespace-only text; it
/// does not enforce uniqueness or check for prior use, which depends on the
/// operation the key is scoped to.
/// </para>
/// </remarks>
public readonly record struct IdempotencyKey
{
    /// <summary>
    /// Initializes a new instance of the <see cref="IdempotencyKey"/>
    /// struct, validating that it carries usable key text.
    /// </summary>
    /// <param name="value">The non-empty canonical idempotency key text.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="value"/> is null, empty, or consists only of
    /// whitespace.
    /// </exception>
    public IdempotencyKey(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        Value = value;
    }

    /// <summary>Gets the canonical idempotency key text.</summary>
    public string Value { get; }

    /// <summary>
    /// Returns the canonical key text, suitable for logging and diagnostic
    /// messages.
    /// </summary>
    public override string ToString() => Value;
}
