// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit;

/// <summary>
/// Identifies the authenticated principal — a human user or a service
/// identity — on whose behalf an operation is performed.
/// </summary>
/// <remarks>
/// <para>
/// This type is an immutable value object with structural (ordinal, textual)
/// equality over <see cref="Value"/>. It carries no mutable state itself and
/// is safe to share and compare across threads without synchronization.
/// </para>
/// <para>
/// A <see cref="PrincipalId"/> is authenticated at a trusted ingress and
/// then carried, unchanged, through every session, run, tool call, and
/// security audit record that principal causes. It is never generated by
/// AgentKit and never itself grants authority: every protected operation
/// still evaluates the principal against the configured security policy,
/// and a component that can technically perform a side effect is not
/// thereby authorized to perform it on this principal's behalf.
/// </para>
/// <para>
/// Because this identifier is caller-supplied text rather than a
/// framework-generated GUID, this constructor only rejects null, empty, and
/// whitespace-only values; it cannot and does not verify that the principal
/// is actually authenticated or currently valid.
/// </para>
/// </remarks>
public readonly record struct PrincipalId
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PrincipalId"/> struct,
    /// validating that it carries usable identifier text.
    /// </summary>
    /// <param name="value">The non-empty canonical principal identifier text.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="value"/> is null, empty, or consists only of
    /// whitespace.
    /// </exception>
    public PrincipalId(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        Value = value;
    }

    /// <summary>Gets the canonical principal identifier text.</summary>
    public string Value { get; }

    /// <summary>
    /// Returns the canonical identifier text, suitable for logging and audit
    /// trails. Callers should still apply their own redaction policy if the
    /// principal identifier is considered personally identifying.
    /// </summary>
    public override string ToString() => Value;
}
