// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit;

/// <summary>Identifies one immutable request evaluated by a security authority.</summary>
/// <remarks>The identifier is generated by an injected <see cref="IIdentifierGenerator{TIdentifier}"/> and is stable across decision, approval, grant, enforcement, and audit records.</remarks>
public readonly record struct SecurityRequestId
{
    /// <summary>Initializes a validated security-request identifier.</summary>
    /// <param name="value">The non-empty globally unique value.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="value"/> is empty.</exception>
    public SecurityRequestId(Guid value)
    {
        ArgumentOutOfRangeException.ThrowIfEqual(value, Guid.Empty);
        Value = value;
    }

    /// <summary>Gets the globally unique value.</summary>
    public Guid Value { get; }

    /// <summary>Returns the canonical lowercase identifier text.</summary>
    public override string ToString() => Value.ToString("D");
}
