// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit;

/// <summary>
/// Identifies the tenant on whose behalf an operation is performed, in a
/// multi-tenant deployment where sessions, memory, and authorization
/// decisions must stay isolated per tenant.
/// </summary>
/// <remarks>
/// <para>
/// This type is an immutable value object with structural (ordinal, textual)
/// equality over <see cref="Value"/>. It carries no mutable state itself and
/// is safe to share and compare across threads without synchronization.
/// </para>
/// <para>
/// Unlike the GUID-based identities such as <see cref="RunId"/> or
/// <see cref="MessageId"/>, a <see cref="TenantId"/> is never generated by
/// AgentKit. It comes from a trusted ingress that authenticates the caller —
/// typically an external identity provider or hosting platform — and is then
/// propagated as an immutable value through every downstream request,
/// session, and authorization decision. Identity never grants authority by
/// itself: a valid <see cref="TenantId"/> still has to pass the configured
/// security authority's policy checks before any protected operation
/// proceeds.
/// </para>
/// <para>
/// Because this identifier is caller-supplied text rather than a
/// framework-generated GUID, this constructor only rejects null, empty, and
/// whitespace-only values. It does not, and cannot, guarantee that the text
/// corresponds to a tenant that actually exists; that check belongs to
/// whichever component resolves tenant-scoped state.
/// </para>
/// </remarks>
public readonly record struct TenantId
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TenantId"/> struct,
    /// validating that it carries usable identifier text.
    /// </summary>
    /// <param name="value">The non-empty canonical tenant identifier text.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="value"/> is null, empty, or consists only of
    /// whitespace.
    /// </exception>
    public TenantId(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
        Value = value;
    }

    /// <summary>Gets the canonical tenant identifier text.</summary>
    public string Value { get; }

    /// <summary>
    /// Returns the canonical identifier text, suitable for logging and
    /// diagnostic messages. Callers that display this value to end users
    /// should still consider whether the tenant identifier is sensitive in
    /// their deployment.
    /// </summary>
    public override string ToString() => Value;
}
