// Copyright (c) AgentKit contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

namespace AgentKit.Providers;

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// An immutable reference catalog of models the first-party provider packages can serve, with the
/// limits, capabilities, availability, and list prices their vendors publish.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="Default"/> is loaded once from the <c>known-models.json</c> resource embedded in this
/// assembly. That resource is generated by <c>scripts/import-known-models.mjs</c> from the public
/// OpenClaw model catalog (itself assembled from models.dev and OpenClaw's plugin manifests) and only
/// includes providers for which AgentKit ships an adapter, under AgentKit's own
/// <see cref="ProviderId"/> values. <see cref="Provenance"/> states exactly which upstream revision it
/// came from.
/// </para>
/// <para>
/// This is a "generated vendor-feed snapshot" in the architecture's terms: it is not authoritative
/// runtime discovery, and it never selects or registers a model. It exists so an application can call
/// <see cref="KnownModel.ToDescriptor"/> instead of hand-writing token limits and prices, and so a UI
/// can offer a picker without a live provider call. Instances are immutable and thread-safe.
/// </para>
/// </remarks>
public sealed class KnownModelCatalog
{
    private const string _resourceName = "AgentKit.Providers.Resources.known-models.json";
    private const int _supportedSchemaVersion = 1;
    private const long _maximumResourceBytes = 8 * 1024 * 1024;

    private static readonly Lazy<KnownModelCatalog> _default = new(LoadEmbedded, LazyThreadSafetyMode.ExecutionAndPublication);
    private static readonly JsonSerializerOptions _serializerOptions = new()
    {
        MaxDepth = 8,
        NumberHandling = JsonNumberHandling.Strict,
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Skip,
    };

    private readonly ImmutableDictionary<(ProviderId Provider, ModelId Model), KnownModel> _byIdentity;

    /// <summary>Initializes a catalog from explicit provenance and models.</summary>
    /// <param name="provenance">Where the models came from.</param>
    /// <param name="models">The models, unique by provider and model identifier.</param>
    /// <exception cref="ArgumentNullException"><paramref name="provenance"/> is null.</exception>
    /// <exception cref="ArgumentException"><paramref name="models"/> is default, contains null, or repeats a provider/model pair.</exception>
    public KnownModelCatalog(KnownModelCatalogProvenance provenance, ImmutableArray<KnownModel> models)
    {
        ArgumentNullException.ThrowIfNull(provenance);
        ArgumentException.ThrowIfDefault(models);
        ArgumentException.ThrowIfContainsNull(models);

        var builder = ImmutableDictionary.CreateBuilder<(ProviderId, ModelId), KnownModel>();
        foreach (var model in models)
        {
            if (!builder.TryAdd((model.ProviderId, model.ModelId), model))
            {
                throw new ArgumentException(
                    $"The catalog lists {model.ProviderId.Value}/{model.ModelId.Value} more than once.", nameof(models));
            }
        }

        Provenance = provenance;
        Models = models;
        _byIdentity = builder.ToImmutable();
    }

    /// <summary>Gets the catalog embedded in this assembly.</summary>
    /// <value>One shared immutable instance, parsed on first access.</value>
    /// <exception cref="InvalidOperationException">The embedded resource is missing or malformed. This indicates a broken build, not a runtime condition.</exception>
    public static KnownModelCatalog Default => _default.Value;

    /// <summary>Gets where this catalog's data came from and when it was captured.</summary>
    public KnownModelCatalogProvenance Provenance { get; }

    /// <summary>Gets every model in the catalog, ordered by provider and then model identifier.</summary>
    public ImmutableArray<KnownModel> Models { get; }

    /// <summary>Gets every distinct provider that has at least one model in the catalog.</summary>
    public IEnumerable<ProviderId> Providers => Models.Select(static model => model.ProviderId).Distinct();

    /// <summary>Looks up one model by provider and model identifier.</summary>
    /// <param name="providerId">The AgentKit provider identifier.</param>
    /// <param name="modelId">The provider's own model identifier, compared ordinally.</param>
    /// <param name="model">The matching model when found.</param>
    /// <returns><see langword="true"/> when the catalog knows the model.</returns>
    public bool TryFind(ProviderId providerId, ModelId modelId, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out KnownModel? model) =>
        _byIdentity.TryGetValue((providerId, modelId), out model);

    /// <summary>Returns every model one provider serves, in catalog order.</summary>
    /// <param name="providerId">The AgentKit provider identifier.</param>
    /// <returns>The provider's models, possibly empty.</returns>
    public ImmutableArray<KnownModel> ForProvider(ProviderId providerId) =>
        [.. Models.Where(model => model.ProviderId == providerId)];

    /// <summary>Parses a catalog from JSON in the embedded resource's schema.</summary>
    /// <param name="json">The UTF-8 JSON document.</param>
    /// <returns>The parsed catalog.</returns>
    /// <exception cref="InvalidOperationException">The document is well-formed JSON but not a supported known-models catalog.</exception>
    /// <exception cref="JsonException">The bytes are not well-formed JSON or a member has the wrong JSON kind.</exception>
    public static KnownModelCatalog Parse(ReadOnlySpan<byte> json)
    {
        var document = JsonSerializer.Deserialize<KnownModelCatalogDocument>(json, _serializerOptions)
            ?? throw new InvalidOperationException("The known-models catalog document is null.");
        if (document.SchemaVersion != _supportedSchemaVersion)
        {
            throw new InvalidOperationException($"The known-models catalog schema version must be {_supportedSchemaVersion}.");
        }

        var source = document.Source ?? throw new InvalidOperationException("The known-models catalog is missing its 'source' member.");
        var provenance = new KnownModelCatalogProvenance(
            Required(source.Name, "source.name"),
            source.Url is { IsAbsoluteUri: true } ? source.Url : throw new InvalidOperationException("The known-models catalog source URL must be absolute."),
            source.Commit,
            source.GeneratedAt,
            source.ImportedAt);

        var models = (document.Models ?? throw new InvalidOperationException("The known-models catalog is missing its 'models' member."))
            .Select(Convert)
            .ToImmutableArray();
        return new KnownModelCatalog(provenance, models);
    }

    private static KnownModel Convert(KnownModelCatalogDocument.ModelDocument model)
    {
        Debug.Assert(model is not null, "The deserializer never yields a null array element for a non-nullable element type.");
        var pricing = model.Pricing is { } price
            ? new KnownModelPricing(
                Required(price.Currency, "pricing.currency"),
                price.InputPerMillionTokens,
                price.OutputPerMillionTokens,
                price.CacheReadPerMillionTokens,
                price.CacheWritePerMillionTokens)
            : null;

        return new KnownModel(
            new ProviderId(Required(model.ProviderId, "providerId")),
            new ModelId(Required(model.ModelId, "modelId")),
            Required(model.DisplayName, "displayName"),
            model.Status,
            model.SupportsReasoning,
            model.SupportsVisionInput,
            model.SupportsToolCalls,
            new ModelLimits(model.MaxContextTokens, model.MaxOutputTokens),
            pricing,
            string.IsNullOrWhiteSpace(model.ReplacedBy) ? null : new ModelId(model.ReplacedBy));
    }

    private static string Required(string? value, string member) =>
        string.IsNullOrWhiteSpace(value)
            ? throw new InvalidOperationException($"The known-models catalog member '{member}' must be a non-empty string.")
            : value;

    private static KnownModelCatalog LoadEmbedded()
    {
        using var stream = typeof(KnownModelCatalog).Assembly.GetManifestResourceStream(_resourceName)
            ?? throw new InvalidOperationException($"The embedded resource '{_resourceName}' is missing from the AgentKit.Providers assembly.");
        if (stream.Length > _maximumResourceBytes)
        {
            throw new InvalidOperationException("The embedded known-models catalog exceeds its size bound.");
        }

        using var buffer = new MemoryStream(checked((int) stream.Length));
        stream.CopyTo(buffer);
        return Parse(buffer.GetBuffer().AsSpan(0, checked((int) buffer.Length)));
    }
}
